# Generated by Django 5.2 on 2025-04-26 07:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allotment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_creation',
            name='exam_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
    ]
