# Generated by Django 5.2 on 2025-04-27 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allotment', '0002_alter_exam_creation_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_creation',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='exam_creation',
            name='fib_question',
        ),
        migrations.RemoveField(
            model_name='exam_creation',
            name='mcq_question',
        ),
        migrations.AddField(
            model_name='exam_creation',
            name='exam_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='exam_creation',
            name='fib_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exam_creation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='exam_creation',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam_creation',
            name='mcq_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
