# Generated by Django 5.2 on 2025-04-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_enrollment', '0006_remove_externalcandidate_unique_id_proof'),
        ('exam_allotment', '0003_remove_exam_creation_exam_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateexamassignment',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='candidateexamassignment',
            name='external_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate_enrollment.externalcandidate'),
        ),
        migrations.AddField(
            model_name='candidateexamassignment',
            name='internal_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate_enrollment.internalcandidate'),
        ),
        migrations.DeleteModel(
            name='exam_enrollment',
        ),
    ]
