# Generated by Django 5.2 on 2025-04-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_enrollment', '0006_remove_externalcandidate_unique_id_proof'),
        ('exam_allotment', '0004_remove_candidateexamassignment_enrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('url_link', models.CharField(max_length=500)),
                ('schedule_datetime', models.DateTimeField()),
                ('invitation_sent_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_allotment.exam_creation')),
                ('external_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate_enrollment.externalcandidate')),
                ('internal_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate_enrollment.internalcandidate')),
            ],
            options={
                'db_table': 'exam_assignment',
            },
        ),
        migrations.DeleteModel(
            name='CandidateExamAssignment',
        ),
    ]
