# Generated by Django 5.2 on 2025-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allotment', '0005_examassignment_delete_candidateexamassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='exam_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
