# Generated by Django 5.2 on 2025-04-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allotment', '0006_examassignment_exam_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassignment',
            name='exam_token',
            field=models.CharField(max_length=100),
        ),
    ]
