# Generated by Django 5.2 on 2025-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allotment', '0007_alter_examassignment_exam_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_creation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
