# Generated by Django 5.2 on 2025-04-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allotment', '0008_exam_creation_location_examassignment_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examassignment',
            name='schedule_datetime',
        ),
    ]
