# Generated by Django 5.2 on 2025-05-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_allotment", "0010_examassignment_exam_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examassignment",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
