# Generated by Django 5.2 on 2025-05-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allotment', '0010_examassignment_exam_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_creation',
            name='candidate_type',
            field=models.IntegerField(choices=[(1, 'Internal'), (2, 'External')], default=1),
        ),
    ]
