# Generated by Django 5.2 on 2025-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allotment', '0011_exam_creation_candidate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
