# Generated by Django 5.1.3 on 2025-04-08 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("emp_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "unique_id_proof",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")],
                        max_length=10,
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("registered_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
