# Generated by Django 5.2 on 2025-04-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_enrollment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="email",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="emp_id",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="full_name",
        ),
        migrations.AddField(
            model_name="candidate",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="department_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="designation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="highest_qualification",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="pin_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
