# Generated by Django 5.2 on 2025-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidate_enrollment",
            "0002_remove_candidate_email_remove_candidate_emp_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
