# Generated by Django 5.2 on 2025-04-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidate_enrollment",
            "0004_externalcandidate_internalcandidate_delete_candidate",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="internalcandidate",
            name="password",
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internalcandidate",
            name="user_id",
            field=models.CharField(default=123, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
