# Generated by Django 5.2 on 2025-04-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidate_enrollment",
            "0005_internalcandidate_password_internalcandidate_user_id",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalcandidate",
            name="unique_id_proof",
        ),
    ]
