# Generated by Django 5.2 on 2025-04-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('correct_answers', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fill_blank_question',
            },
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text="List of options like ['A', 'B', 'C', 'D']")),
                ('answer_type', models.CharField(choices=[('Single', 'Single Correct'), ('Multiple', 'Multiple Correct')], max_length=10)),
                ('correct_answers', models.JSONField(help_text="List of correct answers like ['A'] or ['A', 'C']")),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mcq_question',
            },
        ),
    ]
